#!/usr/bin/env ruby

require 'pp'
require 'addressable/uri'
require 'nokogiri'
require 'xapian'
require 'couchrest'
require 'json'
require 'yaml'

require File.dirname(__FILE__) + "/lib/simplehttpclient"

module BookMarker

  class Index
    def initialize(path)

      @path = path
      @prefixes = {'title' => "S", 'url' => "T"}
    end

    def open_for_writing
      FileUtils.mkdir_p(File.dirname(@path)) unless File.exists?(File.dirname(@path))

      @database = Xapian::WritableDatabase.new(@path, Xapian::DB_CREATE_OR_OPEN)
      @indexer = Xapian::TermGenerator.new()
      @indexer.set_flags(Xapian::TermGenerator::FLAG_SPELLING, 0)
      @indexer.database = @database
    end

    def open_for_reading
      @database = Xapian::Database.new(@path)
      @enquire = Xapian::Enquire.new(@database)

      @query_parser = Xapian::QueryParser.new
      @query_parser.database = @database
      @query_parser.add_boolean_prefix('title', @prefixes['title'])
      @query_parser.add_boolean_prefix('url', @prefixes['url'])
    end

    def add(document)
      doc = Xapian::Document.new()

      doc.data = JSON(document)
      @indexer.document = doc
      @indexer.index_text(document[:url], 10, @prefixes['url'])
      @indexer.index_text(document[:body])
      @indexer.index_text(document[:title], 10, @prefixes['title'])
      @database.add_document(doc)
    end

    def run_query(query, number_of_results=100)
      query = @query_parser.parse_query(query,
                          Xapian::QueryParser::FLAG_BOOLEAN | Xapian::QueryParser::FLAG_PHRASE |
                          Xapian::QueryParser::FLAG_LOVEHATE | Xapian::QueryParser::FLAG_WILDCARD)

      @enquire.query = query
      @enquire.sort_by_relevance!
      @matchset = @enquire.mset(0, number_of_results)
      @matchset
    end

    def results(threshold=0.0)
      @matchset.matches.each do |m|
      #  break if m.percent < max_score * threshold
        yield m
      end
    end
  end

  class BM
    UNKNOWN = 0

    def initialize
      @index = Index.new(config[:db][:path])
      couchdb = CouchRest.new("http://localhost:5984")
      @db = couchdb.database('bookmarker')
    end

    def add(url, category)
      begin
        validate_url(url)
        @db.save_doc('_id' => Digest::SHA1.hexdigest(url), :url => url, :category => category, :status => UNKNOWN)
      rescue RestClient::RequestFailed => e
        puts "#{url} already in cache"
      rescue RuntimeError
        puts "Invalid URL"
      end
    end

    def write
      @db.view('bm/unprocessed')["rows"].each do |e|

        doc = e['value']

        begin
          response, html = download_url(doc['url'])
          if response.is_a? Net::HTTPOK
            title, body = process_document(html)

            res = @db.save_doc('_id' => doc['_id'], 'url' => doc['url'], 'category' => doc['category'], 'status' => 200, '_rev' => doc['_rev'])

            if res['ok']
              puts "#{doc['url']} added to index"
            end
            @index.open_for_writing
            @index.add({:url => doc['url'], :title => title, :body => body, :category => doc['category']})
          end
        rescue RuntimeError => e
          if e.message == 'Unsupported scheme'
            puts "Invalid URL"
          end
        rescue SocketError => e
          # There is a problem getting the uri so do nothing. We'll get
          # it next time we're online.
        end
      end
    end

    def search(query)
      begin
        @index.open_for_reading
        @index.run_query(query)
        @index.results do |r|
          yield r
        end
      rescue IOError => e
        puts "You don't appear to have added any urls! Please add some before you search."
      end
    end

    private
    def config
      YAML::load(File.open("#{ENV['HOME']}/.bookmarkerrc").read)
    end

    def validate_url(url)
      u = Addressable::URI::heuristic_parse(url)
      raise "Unsupported scheme" if u.scheme != "http" && u.scheme != "https"
    end

    def download_url(url)
      user_agent = "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.6) Gecko/20070725 Firefox/2.0.0.6"
      agent = SimpleHttpClient.new(user_agent, 20.0)
      return agent.get(url)
    end

    def process_document(html)
      document = Nokogiri(html)
      title = document.search('//title').inner_text.strip
      body = document.search('//body').inner_text.strip
      return title, body
    end
  end
end

def usage
  "usage: #{File.basename($0)} [add|search]"
  exit 1
end

bm = BookMarker::BM.new

if ARGV[0] == 'search'
  search_term = ARGV[1]
  bm.search(search_term) { |r| puts JSON.parse(r.document.data)['url'] }
elsif ARGV[0] == 'add'
  url = ARGV[1]
  if url.nil?
    url = `xsel -o`
    if url.nil? || url.empty?
      usage
    end
  end

  category = (ARGV[2].nil?) ? "unclassified" : ARGV[2]

  bm.add(url, category)
  bm.write
else
  usage
end
